import React, {useState, useEffect} from "react";
import Head from "next/head";
import Script from "next/script";
import Banner from "../components/banner/Banner";
import PopularCategory from "../components/home/PopularCategory";
import ProductBanner from "../components/home/ProductBanner";
import SuggestSection from "../components/home/SuggestSection";
import OfferBanner from "../components/home/OfferBanner";
import TopSellingProduct from "../components/home/TopSellingProduct";
import BrandSection from "../components/home/BrandSection";
import BannerFooter from "../components/home/BannerFooter";
import ProductViewModal from "../components/common/ProductViewModal";
import FeatureProduct from "../components/home/FeatureProduct";
import { useGetAllProductsShopQuery } from "../redux/features/products/productApi";


export default function Home() {

  const pageSize = 8;
  const page = 1;
  const[products, setProducts] = useState([]);
  const[mostPopular, setMostPopular] = useState([]);
 const {isLoading,data, error} = useGetAllProductsShopQuery({page, pageSize});

 useEffect(() => {
   if(isLoading){
     return;
   }
   else if(data){
    console.log(data)
     const productsData = data.products.map(((item) => ({
       _id: item._id,
       name: item.name,
       category: item.category,
       brand: item.brand,
       price: item.price,
       discountPrice: item.discountPrice,
       images: item.images,
       stock: item.stock,
       ratings: item.ratings,
       commentsCount: item.commentsCount,
       purchased: item.purchased,
       isNew: item.isNewProduct,
       isHot: item.isHotProduct,
       discount: item.discount
     })))
     setProducts(productsData);
     const mostPopularProducts = data.mostPopular.map(((item) => ({
      _id: item._id,
      name: item.name,
      category: item.category,
      brand: item.brand,
      price: item.price,
      discountPrice: item.discountPrice,
      images: item.images,
      ratings: item.ratings,
      commentsCount: item.commentsCount,
      purchased: item.purchased,
      isNew: item.isNewProduct,
      isHot: item.isHotProduct,
      discount: item.discount
    })))
     setMostPopular(mostPopularProducts);
   }
   else{
     console.log(error);
   }
 }, [data])
 

  return (
    <>
      <Head>
        <title>Beautime Global | Health & Beauty Store</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/assets/img/sm-logo.svg" />
        <Script async src="https://www.googletagmanager.com/gtag/js?id=G-81GLR4VQK9"></Script>
      <Script>
        {
          ` window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());
        
          gtag('config', 'G-81GLR4VQK9');`
        }
      </Script>
      </Head>

      <ProductViewModal />
      <Banner />
      <PopularCategory />
      <FeatureProduct products={products}/>
      <ProductBanner />
      <SuggestSection />
      <OfferBanner />
      <TopSellingProduct products={mostPopular}/>
      <BrandSection />
      <BannerFooter />
    </>
  );
}



