import React from "react";
import AuthModal from "./AuthModal";
import Topbar from "./Topbar";
import Header from "./Header";
import Head from "next/head";
import Footer from "./Footer";
import { useRouter } from "next/router";
import AdminLayout from "./admin/AdminLayout";

const MainLayout = ({ children }) => {
  const router = useRouter();

  return (
    <>
      <Head>
        <title>Beautime Global | Health & Beauty Store</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/assets/img/sm-logo.svg" />
      </Head>

      {router.pathname.startsWith("/admin") ? (
        <>
          {/* Admin dashboard layout */} 
          {children}
        </>
      ) : (
        <>
          {/* Default layout */}
          <Topbar />
          <AuthModal />
          <Header /> 
          {children}
          <Footer />
        </>
      )}
  </>
  );
};

export default MainLayout;
