import React, { useEffect } from "react";
import AuthModal from "./AuthModal";
import Topbar from "./Topbar";
import Header from "./Header";
import Head from "next/head";
import Footer from "./Footer";

const MainLayout = ({ children }) => {
  return (
    <>
      <Head>
        <title>FOREVER YOUNG Global | Health & Beauty Store</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/assets/img/sm-logo.svg" />
      </Head>
      
      <Topbar />
      <AuthModal />
      <Header />
      {children}
      <Footer />
    </>
  );s
};

export default MainLayout;
